version: "3.7"
services:
  app:
    build:
      args:
        user: ta
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mvc
    container_name: mvc-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
#      - ./docker-compose/app/php.ini:/usr/local/etc/php/php.ini
    networks:
      - mvc
  nginx:
    image: nginx:1.17-alpine
    container_name: some-nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - some
networks:
  mvc:
    driver: bridge
volumes:
  data:
    driver: local
